fetch latest semver CDK

diff --git a/.github/workflows/cdk-publish.yml b/.github/workflows/cdk-publish.yml
--- a/.github/workflows/cdk-publish.yml
+++ b/.github/workflows/cdk-publish.yml
@@ -88,10 +88,14 @@ jobs:
         run: |
           export PATH="/home/runner/.local/bin:$PATH"
           source .venv/bin/activate
-          poetry install --only main
+          pip install --upgrade pip
+          pip install poetry==1.6.1 semver
+
+          # Get the current CDK version
           poetry self add "poetry-dynamic-versioning[plugin]"
           poetry dynamic-versioning
           cdk_version="$(poetry version --short | tr -d '[:space:]')"
+
           if [ -z "$cdk_version" ]; then
             echo "Failed to get CDK version"
             exit 1
@@ -100,8 +104,38 @@ jobs:
             echo "Error: Failed to resolve dynamic CDK version"
             exit 1
           fi
-          echo "Found CDK version: $cdk_version"
-          echo "CDK_VERSION=$cdk_version" >> $GITHUB_ENV
+
+          # Check if the version is a stable SemVer
+          is_valid_semver=$(python -c "import semver; print(semver.VersionInfo.isvalid('$cdk_version'))")
+          is_prerelease=$(python -c "import semver; print(semver.VersionInfo.parse('$cdk_version').prerelease is not None)")
+
+          if [ "$is_valid_semver" = "False" ] || [ "$is_prerelease" = "True" ]; then
+            echo "Non-stable or invalid SemVer detected ($cdk_version). Fetching latest stable version."
+            
+            # Fetch the latest stable version from PyPI
+            latest_stable_version=$(pip index versions airbyte-cdk | grep -Eo '^[ ]*[0-9]+\.[0-9]+\.[0-9]+$' | tail -1 | tr -d '[:space:]')
+            
+            if [ -z "$latest_stable_version" ]; then
+              echo "Failed to fetch the latest stable version."
+              exit 1
+            fi
+            echo "Latest stable CDK version: $latest_stable_version"
+
+            # Install the latest stable version
+            pip install airbyte-cdk==$latest_stable_version
+
+            # Set CDK_VERSION to the latest stable version
+            cdk_version="$latest_stable_version"
+          else
+            echo "Stable SemVer detected ($cdk_version). Proceeding with this version."
+            # Install dependencies as usual
+            poetry install --only main
+          fi
+
+          # Sanitize CDK_VERSION by replacing '+' with '-'
+          sanitized_cdk_version="${cdk_version//+/-}"
+          echo "Found CDK version: $sanitized_cdk_version"
+          echo "CDK_VERSION=$sanitized_cdk_version" >> $GITHUB_ENV
 
       - name: Check if tag already exists
         run: |
